### PR TITLE
feat: add support to `include` && `exclude` files (`options.include|options.exclude`)

### PR DESCRIPTION
**Pull request by evilebottnawi**
### `Issues` 

- Fixes https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/50

### CODE REVIEW

**Comment by damianobarbati** [comment]
@evilebottnawi great job! Is it making into master anytime soon? 🎉

**Comment by damianobarbati** [comment]
@d3viant0ne 🙏🏻

**Comment by damianobarbati** [comment]
@evilebottnawi do I have any way to try this out now? 
It seems like it's going to take long before this pull request will be merged. 

Sorry for pushing so much for this but two different continuous integration services I'm using are timing out on the build phase because of webpack slow minifying => and I know that's happening because of just 2 huge libraries (already published as minified) and once ignored I'll be finally free from this pain.

But I guess this is a scenario for some other devs as well!

**Comment by michael-ciniawsky** [comment]
I will land this within the next 48 hours in case nobody objects or goes ahead as this seems to be g2g with 2 approvals :)

**Comment by damianobarbati** [comment]
Thanks @michael-ciniawsky that's good news, first tester here 🎉

**Comment by evilebottnawi** [comment]
@michael-ciniawsky friendly ping :+1:

**Comment by michael-ciniawsky** [comment]
Unfortunately I just saw I can't cut a release for `babel-minify-webpack-plugin` 😞 

@boopathi Could you release this when you have a few minutes please ? :)

**Comment by damianobarbati** [comment]
@boopathi @michael-ciniawsky 🙏🏻

**Comment by damianobarbati** [comment]
So no luck on this? 😔

**Comment by evilebottnawi** [comment]
@damianobarbati merged, wait release

**Comment by damianobarbati** [comment]
thanks @evilebottnawi! is this going to happen anytime soon?

**Comment by evilebottnawi** [comment]
@damianobarbati sorry for delay, i am very busy, try to find time today

**Comment by damianobarbati** [comment]
Thanks @evilebottnawi

**Comment by michael-ciniawsky** [comment]
Released in [v0.3.0](https://github.com/webpack-contrib/babel-minify-webpack-plugin/releases/tag/v0.3.0) 🎉

**Pull request merged**
